//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sotec_web.n11Api_SettlementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="n11Api_SettlementService.SettlementServicePort")]
    public interface SettlementServicePort {
        
        // CODEGEN: GetSettlementList işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_SettlementService.GetSettlementListResponse1 GetSettlementList(sotec_web.n11Api_SettlementService.GetSettlementListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementListResponse1> GetSettlementListAsync(sotec_web.n11Api_SettlementService.GetSettlementListRequest1 request);
        
        // CODEGEN: GetSettlementDetail işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1 GetSettlementDetail(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1> GetSettlementDetailAsync(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSettlementListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string startDateField;
        
        private string endDateField;
        
        private RequestPagingData pagingDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public RequestPagingData pagingData {
            get {
                return this.pagingDataField;
            }
            set {
                this.pagingDataField = value;
                this.RaisePropertyChanged("pagingData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DefermentSettlementUsageData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        private string orderDateField;
        
        private long productIdField;
        
        private string productTitleField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
                this.RaisePropertyChanged("orderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string productTitle {
            get {
                return this.productTitleField;
            }
            set {
                this.productTitleField = value;
                this.RaisePropertyChanged("productTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DefermentSppDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        private string campaignNumberField;
        
        private string createdDateField;
        
        private decimal cargoWeightFromShipmentCompanyField;
        
        private decimal deferredAmountField;
        
        private string shipmentCompanyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string campaignNumber {
            get {
                return this.campaignNumberField;
            }
            set {
                this.campaignNumberField = value;
                this.RaisePropertyChanged("campaignNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("createdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal cargoWeightFromShipmentCompany {
            get {
                return this.cargoWeightFromShipmentCompanyField;
            }
            set {
                this.cargoWeightFromShipmentCompanyField = value;
                this.RaisePropertyChanged("cargoWeightFromShipmentCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal deferredAmount {
            get {
                return this.deferredAmountField;
            }
            set {
                this.deferredAmountField = value;
                this.RaisePropertyChanged("deferredAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string shipmentCompanyName {
            get {
                return this.shipmentCompanyNameField;
            }
            set {
                this.shipmentCompanyNameField = value;
                this.RaisePropertyChanged("shipmentCompanyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DefermentDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deferredDateField;
        
        private decimal amountField;
        
        private string defermentReasonDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deferredDate {
            get {
                return this.deferredDateField;
            }
            set {
                this.deferredDateField = value;
                this.RaisePropertyChanged("deferredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string defermentReasonDetail {
            get {
                return this.defermentReasonDetailField;
            }
            set {
                this.defermentReasonDetailField = value;
                this.RaisePropertyChanged("defermentReasonDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DefermentSettlementUsageDataList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal financialTotalDefermentField;
        
        private decimal totalReturnDefermentAmountField;
        
        private DefermentDTO[] defermentsField;
        
        private DefermentSppDTO[] defermentSppUsagesField;
        
        private DefermentSettlementUsageData[] defermentSettlementUsagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal financialTotalDeferment {
            get {
                return this.financialTotalDefermentField;
            }
            set {
                this.financialTotalDefermentField = value;
                this.RaisePropertyChanged("financialTotalDeferment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal totalReturnDefermentAmount {
            get {
                return this.totalReturnDefermentAmountField;
            }
            set {
                this.totalReturnDefermentAmountField = value;
                this.RaisePropertyChanged("totalReturnDefermentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("deferment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DefermentDTO[] deferments {
            get {
                return this.defermentsField;
            }
            set {
                this.defermentsField = value;
                this.RaisePropertyChanged("deferments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("defermentSppUsage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DefermentSppDTO[] defermentSppUsages {
            get {
                return this.defermentSppUsagesField;
            }
            set {
                this.defermentSppUsagesField = value;
                this.RaisePropertyChanged("defermentSppUsages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("defermentSettlementUsage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DefermentSettlementUsageData[] defermentSettlementUsages {
            get {
                return this.defermentSettlementUsagesField;
            }
            set {
                this.defermentSettlementUsagesField = value;
                this.RaisePropertyChanged("defermentSettlementUsages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class OrderItemSettlementData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal adFeeField;
        
        private bool adFeeFieldSpecified;
        
        private decimal adFeeVatField;
        
        private bool adFeeVatFieldSpecified;
        
        private string buyerEmailField;
        
        private string buyerNameField;
        
        private decimal commissionField;
        
        private bool commissionFieldSpecified;
        
        private string completedDateField;
        
        private decimal deductionAmountField;
        
        private bool deductionAmountFieldSpecified;
        
        private long orderItemIdField;
        
        private bool orderItemIdFieldSpecified;
        
        private string orderNumberField;
        
        private decimal paymentAmountField;
        
        private bool paymentAmountFieldSpecified;
        
        private string paymentDateField;
        
        private long productIdField;
        
        private bool productIdFieldSpecified;
        
        private string productNameField;
        
        private string remittanceDateField;
        
        private decimal sellerCouponDiscountField;
        
        private bool sellerCouponDiscountFieldSpecified;
        
        private decimal sellerDiscountField;
        
        private bool sellerDiscountFieldSpecified;
        
        private decimal settlementAmountField;
        
        private bool settlementAmountFieldSpecified;
        
        private string settlementDateField;
        
        private string shippingDateField;
        
        private string trackingNumberField;
        
        private decimal defermentOfPaymentField;
        
        private bool defermentOfPaymentFieldSpecified;
        
        private decimal cargoPriceField;
        
        private bool cargoPriceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal adFee {
            get {
                return this.adFeeField;
            }
            set {
                this.adFeeField = value;
                this.RaisePropertyChanged("adFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adFeeSpecified {
            get {
                return this.adFeeFieldSpecified;
            }
            set {
                this.adFeeFieldSpecified = value;
                this.RaisePropertyChanged("adFeeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal adFeeVat {
            get {
                return this.adFeeVatField;
            }
            set {
                this.adFeeVatField = value;
                this.RaisePropertyChanged("adFeeVat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adFeeVatSpecified {
            get {
                return this.adFeeVatFieldSpecified;
            }
            set {
                this.adFeeVatFieldSpecified = value;
                this.RaisePropertyChanged("adFeeVatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string buyerEmail {
            get {
                return this.buyerEmailField;
            }
            set {
                this.buyerEmailField = value;
                this.RaisePropertyChanged("buyerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string buyerName {
            get {
                return this.buyerNameField;
            }
            set {
                this.buyerNameField = value;
                this.RaisePropertyChanged("buyerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
                this.RaisePropertyChanged("commission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commissionSpecified {
            get {
                return this.commissionFieldSpecified;
            }
            set {
                this.commissionFieldSpecified = value;
                this.RaisePropertyChanged("commissionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string completedDate {
            get {
                return this.completedDateField;
            }
            set {
                this.completedDateField = value;
                this.RaisePropertyChanged("completedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal deductionAmount {
            get {
                return this.deductionAmountField;
            }
            set {
                this.deductionAmountField = value;
                this.RaisePropertyChanged("deductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deductionAmountSpecified {
            get {
                return this.deductionAmountFieldSpecified;
            }
            set {
                this.deductionAmountFieldSpecified = value;
                this.RaisePropertyChanged("deductionAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long orderItemId {
            get {
                return this.orderItemIdField;
            }
            set {
                this.orderItemIdField = value;
                this.RaisePropertyChanged("orderItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderItemIdSpecified {
            get {
                return this.orderItemIdFieldSpecified;
            }
            set {
                this.orderItemIdFieldSpecified = value;
                this.RaisePropertyChanged("orderItemIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal paymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
                this.RaisePropertyChanged("paymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentAmountSpecified {
            get {
                return this.paymentAmountFieldSpecified;
            }
            set {
                this.paymentAmountFieldSpecified = value;
                this.RaisePropertyChanged("paymentAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("paymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string remittanceDate {
            get {
                return this.remittanceDateField;
            }
            set {
                this.remittanceDateField = value;
                this.RaisePropertyChanged("remittanceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal sellerCouponDiscount {
            get {
                return this.sellerCouponDiscountField;
            }
            set {
                this.sellerCouponDiscountField = value;
                this.RaisePropertyChanged("sellerCouponDiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sellerCouponDiscountSpecified {
            get {
                return this.sellerCouponDiscountFieldSpecified;
            }
            set {
                this.sellerCouponDiscountFieldSpecified = value;
                this.RaisePropertyChanged("sellerCouponDiscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal sellerDiscount {
            get {
                return this.sellerDiscountField;
            }
            set {
                this.sellerDiscountField = value;
                this.RaisePropertyChanged("sellerDiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sellerDiscountSpecified {
            get {
                return this.sellerDiscountFieldSpecified;
            }
            set {
                this.sellerDiscountFieldSpecified = value;
                this.RaisePropertyChanged("sellerDiscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal settlementAmount {
            get {
                return this.settlementAmountField;
            }
            set {
                this.settlementAmountField = value;
                this.RaisePropertyChanged("settlementAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settlementAmountSpecified {
            get {
                return this.settlementAmountFieldSpecified;
            }
            set {
                this.settlementAmountFieldSpecified = value;
                this.RaisePropertyChanged("settlementAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string settlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
                this.RaisePropertyChanged("settlementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string shippingDate {
            get {
                return this.shippingDateField;
            }
            set {
                this.shippingDateField = value;
                this.RaisePropertyChanged("shippingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("trackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal defermentOfPayment {
            get {
                return this.defermentOfPaymentField;
            }
            set {
                this.defermentOfPaymentField = value;
                this.RaisePropertyChanged("defermentOfPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defermentOfPaymentSpecified {
            get {
                return this.defermentOfPaymentFieldSpecified;
            }
            set {
                this.defermentOfPaymentFieldSpecified = value;
                this.RaisePropertyChanged("defermentOfPaymentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal cargoPrice {
            get {
                return this.cargoPriceField;
            }
            set {
                this.cargoPriceField = value;
                this.RaisePropertyChanged("cargoPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cargoPriceSpecified {
            get {
                return this.cargoPriceFieldSpecified;
            }
            set {
                this.cargoPriceFieldSpecified = value;
                this.RaisePropertyChanged("cargoPriceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class OrderItemSettlementDataList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PagingData metadataField;
        
        private OrderItemSettlementData[] orderItemSettlementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PagingData metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("orderItemSettlement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public OrderItemSettlementData[] orderItemSettlements {
            get {
                return this.orderItemSettlementsField;
            }
            set {
                this.orderItemSettlementsField = value;
                this.RaisePropertyChanged("orderItemSettlements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class PagingData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> currentPageField;
        
        private System.Nullable<int> pageSizeField;
        
        private System.Nullable<long> totalCountField;
        
        private System.Nullable<int> pageCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<long> totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
                this.RaisePropertyChanged("pageCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SettlementDetailSummaryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal salesAmountField;
        
        private decimal sellerWithdrawField;
        
        private decimal releaseDefermentField;
        
        private decimal deductionAmountField;
        
        private decimal defermentOfPaymentField;
        
        private decimal paymentToECashField;
        
        private decimal remittanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal salesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
                this.RaisePropertyChanged("salesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sellerWithdraw {
            get {
                return this.sellerWithdrawField;
            }
            set {
                this.sellerWithdrawField = value;
                this.RaisePropertyChanged("sellerWithdraw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal releaseDeferment {
            get {
                return this.releaseDefermentField;
            }
            set {
                this.releaseDefermentField = value;
                this.RaisePropertyChanged("releaseDeferment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal deductionAmount {
            get {
                return this.deductionAmountField;
            }
            set {
                this.deductionAmountField = value;
                this.RaisePropertyChanged("deductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal defermentOfPayment {
            get {
                return this.defermentOfPaymentField;
            }
            set {
                this.defermentOfPaymentField = value;
                this.RaisePropertyChanged("defermentOfPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal paymentToECash {
            get {
                return this.paymentToECashField;
            }
            set {
                this.paymentToECashField = value;
                this.RaisePropertyChanged("paymentToECash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal remittance {
            get {
                return this.remittanceField;
            }
            set {
                this.remittanceField = value;
                this.RaisePropertyChanged("remittance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SettlementDetailData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SettlementDetailSummaryData settlementField;
        
        private OrderItemSettlementDataList orderItemSettlementDataListField;
        
        private DefermentSettlementUsageDataList defermentSettlementUsageDataListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SettlementDetailSummaryData settlement {
            get {
                return this.settlementField;
            }
            set {
                this.settlementField = value;
                this.RaisePropertyChanged("settlement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrderItemSettlementDataList orderItemSettlementDataList {
            get {
                return this.orderItemSettlementDataListField;
            }
            set {
                this.orderItemSettlementDataListField = value;
                this.RaisePropertyChanged("orderItemSettlementDataList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DefermentSettlementUsageDataList defermentSettlementUsageDataList {
            get {
                return this.defermentSettlementUsageDataListField;
            }
            set {
                this.defermentSettlementUsageDataListField = value;
                this.RaisePropertyChanged("defermentSettlementUsageDataList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SettlementSummaryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal paymentAmountField;
        
        private decimal deductionAmountField;
        
        private decimal settlementAmountField;
        
        private string settlementDateField;
        
        private string remittanceDateField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal paymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
                this.RaisePropertyChanged("paymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal deductionAmount {
            get {
                return this.deductionAmountField;
            }
            set {
                this.deductionAmountField = value;
                this.RaisePropertyChanged("deductionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal settlementAmount {
            get {
                return this.settlementAmountField;
            }
            set {
                this.settlementAmountField = value;
                this.RaisePropertyChanged("settlementAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string settlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
                this.RaisePropertyChanged("settlementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remittanceDate {
            get {
                return this.remittanceDateField;
            }
            set {
                this.remittanceDateField = value;
                this.RaisePropertyChanged("remittanceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SettlementSummaryDataList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SettlementSummaryData[] settlementListField;
        
        private PagingData metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("settlementList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SettlementSummaryData[] settlementList {
            get {
                return this.settlementListField;
            }
            set {
                this.settlementListField = value;
                this.RaisePropertyChanged("settlementList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PagingData metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class RequestPagingData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> currentPageField;
        
        private System.Nullable<int> pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSettlementListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private SettlementSummaryDataList settlementListDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SettlementSummaryDataList settlementListData {
            get {
                return this.settlementListDataField;
            }
            set {
                this.settlementListDataField = value;
                this.RaisePropertyChanged("settlementListData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettlementListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_SettlementService.GetSettlementListRequest GetSettlementListRequest;
        
        public GetSettlementListRequest1() {
        }
        
        public GetSettlementListRequest1(sotec_web.n11Api_SettlementService.GetSettlementListRequest GetSettlementListRequest) {
            this.GetSettlementListRequest = GetSettlementListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettlementListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_SettlementService.GetSettlementListResponse GetSettlementListResponse;
        
        public GetSettlementListResponse1() {
        }
        
        public GetSettlementListResponse1(sotec_web.n11Api_SettlementService.GetSettlementListResponse GetSettlementListResponse) {
            this.GetSettlementListResponse = GetSettlementListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSettlementDetailRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string dateField;
        
        private RequestPagingData pagingDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RequestPagingData pagingData {
            get {
                return this.pagingDataField;
            }
            set {
                this.pagingDataField = value;
                this.RaisePropertyChanged("pagingData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSettlementDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private SettlementDetailData settlementDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SettlementDetailData settlementDetail {
            get {
                return this.settlementDetailField;
            }
            set {
                this.settlementDetailField = value;
                this.RaisePropertyChanged("settlementDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettlementDetailRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_SettlementService.GetSettlementDetailRequest GetSettlementDetailRequest;
        
        public GetSettlementDetailRequest1() {
        }
        
        public GetSettlementDetailRequest1(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest GetSettlementDetailRequest) {
            this.GetSettlementDetailRequest = GetSettlementDetailRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettlementDetailResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_SettlementService.GetSettlementDetailResponse GetSettlementDetailResponse;
        
        public GetSettlementDetailResponse1() {
        }
        
        public GetSettlementDetailResponse1(sotec_web.n11Api_SettlementService.GetSettlementDetailResponse GetSettlementDetailResponse) {
            this.GetSettlementDetailResponse = GetSettlementDetailResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SettlementServicePortChannel : sotec_web.n11Api_SettlementService.SettlementServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SettlementServicePortClient : System.ServiceModel.ClientBase<sotec_web.n11Api_SettlementService.SettlementServicePort>, sotec_web.n11Api_SettlementService.SettlementServicePort {
        
        public SettlementServicePortClient() {
        }
        
        public SettlementServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettlementServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettlementServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettlementServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_SettlementService.GetSettlementListResponse1 sotec_web.n11Api_SettlementService.SettlementServicePort.GetSettlementList(sotec_web.n11Api_SettlementService.GetSettlementListRequest1 request) {
            return base.Channel.GetSettlementList(request);
        }
        
        public sotec_web.n11Api_SettlementService.GetSettlementListResponse GetSettlementList(sotec_web.n11Api_SettlementService.GetSettlementListRequest GetSettlementListRequest) {
            sotec_web.n11Api_SettlementService.GetSettlementListRequest1 inValue = new sotec_web.n11Api_SettlementService.GetSettlementListRequest1();
            inValue.GetSettlementListRequest = GetSettlementListRequest;
            sotec_web.n11Api_SettlementService.GetSettlementListResponse1 retVal = ((sotec_web.n11Api_SettlementService.SettlementServicePort)(this)).GetSettlementList(inValue);
            return retVal.GetSettlementListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementListResponse1> sotec_web.n11Api_SettlementService.SettlementServicePort.GetSettlementListAsync(sotec_web.n11Api_SettlementService.GetSettlementListRequest1 request) {
            return base.Channel.GetSettlementListAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementListResponse1> GetSettlementListAsync(sotec_web.n11Api_SettlementService.GetSettlementListRequest GetSettlementListRequest) {
            sotec_web.n11Api_SettlementService.GetSettlementListRequest1 inValue = new sotec_web.n11Api_SettlementService.GetSettlementListRequest1();
            inValue.GetSettlementListRequest = GetSettlementListRequest;
            return ((sotec_web.n11Api_SettlementService.SettlementServicePort)(this)).GetSettlementListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1 sotec_web.n11Api_SettlementService.SettlementServicePort.GetSettlementDetail(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 request) {
            return base.Channel.GetSettlementDetail(request);
        }
        
        public sotec_web.n11Api_SettlementService.GetSettlementDetailResponse GetSettlementDetail(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest GetSettlementDetailRequest) {
            sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 inValue = new sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1();
            inValue.GetSettlementDetailRequest = GetSettlementDetailRequest;
            sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1 retVal = ((sotec_web.n11Api_SettlementService.SettlementServicePort)(this)).GetSettlementDetail(inValue);
            return retVal.GetSettlementDetailResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1> sotec_web.n11Api_SettlementService.SettlementServicePort.GetSettlementDetailAsync(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 request) {
            return base.Channel.GetSettlementDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_SettlementService.GetSettlementDetailResponse1> GetSettlementDetailAsync(sotec_web.n11Api_SettlementService.GetSettlementDetailRequest GetSettlementDetailRequest) {
            sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1 inValue = new sotec_web.n11Api_SettlementService.GetSettlementDetailRequest1();
            inValue.GetSettlementDetailRequest = GetSettlementDetailRequest;
            return ((sotec_web.n11Api_SettlementService.SettlementServicePort)(this)).GetSettlementDetailAsync(inValue);
        }
    }
}
