//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sotec_web.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dil() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sotec_web.Resources.Dil", typeof(Dil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DESCRIPTION benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AÇIKLAMA {
            get {
                return ResourceManager.GetString("AÇIKLAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AD_SOYAD {
            get {
                return ResourceManager.GetString("AD SOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADRESS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ADRES {
            get {
                return ResourceManager.GetString("ADRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADRESS NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ADRES_ADI {
            get {
                return ResourceManager.GetString("ADRES ADI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADRESS SETINGS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ADRESLERİ_DÜZENLE {
            get {
                return ResourceManager.GetString("ADRESLERİ DÜZENLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTIUNE SHOPING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ALIŞVERİŞE_DEVAM_ET {
            get {
                return ResourceManager.GetString("ALIŞVERİŞE DEVAM ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUB TOTAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ALT_TOPLAM {
            get {
                return ResourceManager.GetString("ALT TOPLAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ANA_SAYFA {
            get {
                return ResourceManager.GetString("ANA SAYFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PENDING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BEKLEMEDE {
            get {
                return ResourceManager.GetString("BEKLEMEDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLOG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BLOG {
            get {
                return ResourceManager.GetString("BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AVENUE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CADDE {
            get {
                return ResourceManager.GetString("CADDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOURS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÇALIŞMA_SAATLERİ {
            get {
                return ResourceManager.GetString("ÇALIŞMA SAATLERİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SING OUT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÇIKIŞ_YAP {
            get {
                return ResourceManager.GetString("ÇIKIŞ YAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READ MORE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DEVAMINI_OKU {
            get {
                return ResourceManager.GetString("DEVAMINI OKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LANGUAGES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DİLLER {
            get {
                return ResourceManager.GetString("DİLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DURUM {
            get {
                return ResourceManager.GetString("DURUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDİT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DÜZENLE {
            get {
                return ResourceManager.GetString("DÜZENLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-MAİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string E_MAİL {
            get {
                return ResourceManager.GetString("E-MAİL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eksik bilgi girdiniz lütfen tüm alanları doldurun benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ekisk_bilgi_girdiniz_lğtfen_tüm_alanları_doldurun {
            get {
                return ResourceManager.GetString("Ekisk bilgi girdiniz lğtfen tüm alanları doldurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARE YOU SURE? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EMİN_MİSİNİZ_ {
            get {
                return ResourceManager.GetString("EMİN MİSİNİZ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OLD PASSWORD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ESKİ_ŞİFRE {
            get {
                return ResourceManager.GetString("ESKİ ŞİFRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EVET {
            get {
                return ResourceManager.GetString("EVET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRICE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FİYAT {
            get {
                return ResourceManager.GetString("FİYAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GRAND TOTAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GENEL_TOPLAM {
            get {
                return ResourceManager.GetString("GENEL TOPLAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BACK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GERİ {
            get {
                return ResourceManager.GetString("GERİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SING IN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GİRİŞ_YAP {
            get {
                return ResourceManager.GetString("GİRİŞ YAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Gizlilik_Politikası {
            get {
                return ResourceManager.GetString("Gizlilik Politikası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEND benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GÖNDER {
            get {
                return ResourceManager.GetString("GÖNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GSM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GÜNCELLE {
            get {
                return ResourceManager.GetString("GÜNCELLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEWS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HABERLER {
            get {
                return ResourceManager.GetString("HABERLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ABOUT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HAKKIMIZDA {
            get {
                return ResourceManager.GetString("HAKKIMIZDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRANSFER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HAVALE {
            get {
                return ResourceManager.GetString("HAVALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HAYIR {
            get {
                return ResourceManager.GetString("HAYIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PREPERING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HAZIRLANIYOR {
            get {
                return ResourceManager.GetString("HAZIRLANIYOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACOUNT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HESAP {
            get {
                return ResourceManager.GetString("HESAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACOUNT DETAILS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HESAP_DETAYLARI {
            get {
                return ResourceManager.GetString("HESAP DETAYLARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVİCES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HİZMETLER {
            get {
                return ResourceManager.GetString("HİZMETLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTACT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İLETİŞİM {
            get {
                return ResourceManager.GetString("İLETİŞİM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCELED benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İPTAL_EDİLDİ {
            get {
                return ResourceManager.GetString("İPTAL EDİLDİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WİSHLİST benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İSTEK_LİSTESİ {
            get {
                return ResourceManager.GetString("İSTEK LİSTESİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLOSE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KAPAT {
            get {
                return ResourceManager.GetString("KAPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAY AT THE DOOR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KAPIDA_ÖDEME {
            get {
                return ResourceManager.GetString("KAPIDA ÖDEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CARGO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KARGO {
            get {
                return ResourceManager.GetString("KARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CARGO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KARGODA {
            get {
                return ResourceManager.GetString("KARGODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CATEGORIES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KATEGORİLER {
            get {
                return ResourceManager.GetString("KATEGORİLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KAYDET {
            get {
                return ResourceManager.GetString("KAYDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REGISTER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KAYIT_OL {
            get {
                return ResourceManager.GetString("KAYIT OL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUBJECT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KONU {
            get {
                return ResourceManager.GetString("KONU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREDİT CART benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KREDİ_KARTI {
            get {
                return ResourceManager.GetString("KREDİ KARTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of use benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kullanım_Şartları {
            get {
                return ResourceManager.GetString("Kullanım Şartları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MAĞAZA {
            get {
                return ResourceManager.GetString("MAĞAZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELIVERY FROM THE STORE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MAĞAZADAN_TESLİM {
            get {
                return ResourceManager.GetString("MAĞAZADAN TESLİM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEIGHBORHOOD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MAHALLE {
            get {
                return ResourceManager.GetString("MAHALLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MENU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MENÜ {
            get {
                return ResourceManager.GetString("MENÜ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance Selling Contract benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesafeli_Satış_Sözleşmesi {
            get {
                return ResourceManager.GetString("Mesafeli Satış Sözleşmesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MESSAGE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MESAJ {
            get {
                return ResourceManager.GetString("MESAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajınız alındı, en kısa sürede size dönüş yapacağız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesajınız_alındı__en_kısa_sürede_size_dönüş_yapacağız_ {
            get {
                return ResourceManager.GetString("Mesajınız alındı, en kısa sürede size dönüş yapacağız.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MİKTAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MİKTAR {
            get {
                return ResourceManager.GetString("MİKTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NOTE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖDEME {
            get {
                return ResourceManager.GetString("ÖDEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAYMENT METHOD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖDEME_TİPİ {
            get {
                return ResourceManager.GetString("ÖDEME TİPİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROCEED TO CHECKOUT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖDEMEYE_GEÇ {
            get {
                return ResourceManager.GetString("ÖDEMEYE GEÇ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÖN SİPARİŞ VER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖN_SİPARİŞ_VER {
            get {
                return ResourceManager.GetString("ÖN SİPARİŞ VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRENDING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖNE_ÇIKANLAR {
            get {
                return ResourceManager.GetString("ÖNE ÇIKANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POST CODE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string POSTA_KODU {
            get {
                return ResourceManager.GetString("POSTA KODU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROJECTS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PROJELERIMIZ {
            get {
                return ResourceManager.GetString("PROJELERIMIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REFFERANCES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string REFERANSLAR {
            get {
                return ResourceManager.GetString("REFERANSLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SATIN_AL {
            get {
                return ResourceManager.GetString("SATIN AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CHOOSE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SEÇİNİZ {
            get {
                return ResourceManager.GetString("SEÇİNİZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CITY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ŞEHİR {
            get {
                return ResourceManager.GetString("ŞEHİR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISTRICT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SEMT {
            get {
                return ResourceManager.GetString("SEMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOPPING CART benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SEPET {
            get {
                return ResourceManager.GetString("SEPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD TO CART benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SEPETE_EKLE {
            get {
                return ResourceManager.GetString("SEPETE EKLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIEV CART benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SEPETE_GİT {
            get {
                return ResourceManager.GetString("SEPETE GİT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Products in the Cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sepetinizde_Hiç_Ürün_Yok {
            get {
                return ResourceManager.GetString("Sepetinizde Hiç Ürün Yok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PASSWORD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ŞİFRE {
            get {
                return ResourceManager.GetString("ŞİFRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lost Your Password? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Şifremi_Ununttum {
            get {
                return ResourceManager.GetString("Şifremi Ununttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAQ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sık_Sorulan_Sorular {
            get {
                return ResourceManager.GetString("Sık Sorulan Sorular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SİL {
            get {
                return ResourceManager.GetString("SİL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ORDER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SİPARİŞ {
            get {
                return ResourceManager.GetString("SİPARİŞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have received your order, check your order&apos;s account or check by mail, have a nice shopping. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Siparişiniz_bize_ulaşmıştır {
            get {
                return ResourceManager.GetString("Siparişiniz bize ulaşmıştır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have received your order, you can make your payment to the account number below with your order number, have a nice shopping. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Siparişiniz_bize_ulaşmıştır_HAVALE {
            get {
                return ResourceManager.GetString("Siparişiniz bize ulaşmıştır HAVALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We have received your order, you can receive your order from our store, have a nice shopping. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Siparişiniz_bize_ulaşmıştır_MAĞAZA {
            get {
                return ResourceManager.GetString("Siparişiniz bize ulaşmıştır MAĞAZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ORDERS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SİPARİŞLER {
            get {
                return ResourceManager.GetString("SİPARİŞLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STREET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SOKAK {
            get {
                return ResourceManager.GetString("SOKAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LATEST FROM BLOG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SON_BLOG_YAZILARI {
            get {
                return ResourceManager.GetString("SON BLOG YAZILARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SURNAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SOYAD {
            get {
                return ResourceManager.GetString("SOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOCK CODE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string STOK_KODU {
            get {
                return ResourceManager.GetString("STOK KODU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OUT OF STOCK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string STOKTA_YOK {
            get {
                return ResourceManager.GetString("STOKTA YOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMPLETED benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TAMAMLANDI {
            get {
                return ResourceManager.GetString("TAMAMLANDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TARİH {
            get {
                return ResourceManager.GetString("TARİH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TELEPHONE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TELEFON {
            get {
                return ResourceManager.GetString("TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TEMİZLE {
            get {
                return ResourceManager.GetString("TEMİZLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEŞEKKÜRLER! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TEŞEKKÜRLER_ {
            get {
                return ResourceManager.GetString("TEŞEKKÜRLER!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOTAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TOPLAM {
            get {
                return ResourceManager.GetString("TOPLAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Right Reserved benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tüm_Hakları_Saklıdır {
            get {
                return ResourceManager.GetString("Tüm Hakları Saklıdır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COUNTRY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÜLKE {
            get {
                return ResourceManager.GetString("ÜLKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Added to Cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ürün_Sepete_Eklendi___ {
            get {
                return ResourceManager.GetString("Ürün Sepete Eklendi...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Removed from Cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ürün_Sepetten_Silindi {
            get {
                return ResourceManager.GetString("Ürün Sepetten Silindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRODUCTS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string URUNLERIMIZ {
            get {
                return ResourceManager.GetString("URUNLERIMIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRODUCTS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÜRÜNLERİMİZ {
            get {
                return ResourceManager.GetString("ÜRÜNLERİMİZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   continue with benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string üye_olmadan_devam_et {
            get {
                return ResourceManager.GetString("üye olmadan devam et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Membership Agreement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Üyelik_Sözleşmesi {
            get {
                return ResourceManager.GetString("Üyelik Sözleşmesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WHATSAPP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WHATSAPP {
            get {
                return ResourceManager.GetString("WHATSAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   or benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yada {
            get {
                return ResourceManager.GetString("yada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD NEW ADRESS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YENİ_ADRES_EKLE {
            get {
                return ResourceManager.GetString("YENİ ADRES EKLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YENİ_KULLANICI {
            get {
                return ResourceManager.GetString("YENİ KULLANICI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW PASSWORD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YENİ_ŞİFRE {
            get {
                return ResourceManager.GetString("YENİ ŞİFRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REFRESH benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YENİLE {
            get {
                return ResourceManager.GetString("YENİLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YUKARI {
            get {
                return ResourceManager.GetString("YUKARI", resourceCulture);
            }
        }
    }
}
