//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sotec_web.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dil() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sotec_web.Resources.Dil", typeof(Dil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DESCRIPTION benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AÇIKLAMA {
            get {
                return ResourceManager.GetString("AÇIKLAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AD_SOYAD {
            get {
                return ResourceManager.GetString("AD SOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADRESS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ADRES {
            get {
                return ResourceManager.GetString("ADRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ANA_SAYFA {
            get {
                return ResourceManager.GetString("ANA SAYFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLOG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BLOG {
            get {
                return ResourceManager.GetString("BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOURS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÇALIŞMA_SAATLERİ {
            get {
                return ResourceManager.GetString("ÇALIŞMA SAATLERİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READ MORE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DEVAMINI_OKU {
            get {
                return ResourceManager.GetString("DEVAMINI OKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LANGUAGES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DİLLER {
            get {
                return ResourceManager.GetString("DİLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-MAİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string E_MAİL {
            get {
                return ResourceManager.GetString("E-MAİL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekisk bilgi girdiniz lğtfen tüm alanları doldurun benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ekisk_bilgi_girdiniz_lğtfen_tüm_alanları_doldurun {
            get {
                return ResourceManager.GetString("Ekisk bilgi girdiniz lğtfen tüm alanları doldurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BACK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GERİ {
            get {
                return ResourceManager.GetString("GERİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEND benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GÖNDER {
            get {
                return ResourceManager.GetString("GÖNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GSM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEWS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HABERLER {
            get {
                return ResourceManager.GetString("HABERLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ABOUT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HAKKIMIZDA {
            get {
                return ResourceManager.GetString("HAKKIMIZDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SERVİCES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HİZMETLER {
            get {
                return ResourceManager.GetString("HİZMETLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTACT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İLETİŞİM {
            get {
                return ResourceManager.GetString("İLETİŞİM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLOSE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KAPAT {
            get {
                return ResourceManager.GetString("KAPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CATEGORIES benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KATEGORİLER {
            get {
                return ResourceManager.GetString("KATEGORİLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUBJECT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KONU {
            get {
                return ResourceManager.GetString("KONU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MAĞAZA {
            get {
                return ResourceManager.GetString("MAĞAZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MENU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MENÜ {
            get {
                return ResourceManager.GetString("MENÜ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MESSAGE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MESAJ {
            get {
                return ResourceManager.GetString("MESAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesajınız alındı, en kısa sürede size dönüş yapacağız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesajınız_alındı__en_kısa_sürede_size_dönüş_yapacağız_ {
            get {
                return ResourceManager.GetString("Mesajınız alındı, en kısa sürede size dönüş yapacağız.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRENDING benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ÖNE_ÇIKANLAR {
            get {
                return ResourceManager.GetString("ÖNE ÇIKANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LATEST FROM BLOG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SON_BLOG_YAZILARI {
            get {
                return ResourceManager.GetString("SON BLOG YAZILARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOCK CODE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string STOK_KODU {
            get {
                return ResourceManager.GetString("STOK KODU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TELEPHONE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TELEFON {
            get {
                return ResourceManager.GetString("TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEŞEKKÜRLER! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TEŞEKKÜRLER_ {
            get {
                return ResourceManager.GetString("TEŞEKKÜRLER!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Right Reserved benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tüm_Hakları_Saklıdır {
            get {
                return ResourceManager.GetString("Tüm Hakları Saklıdır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WHATSAPP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WHATSAPP {
            get {
                return ResourceManager.GetString("WHATSAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YUKARI {
            get {
                return ResourceManager.GetString("YUKARI", resourceCulture);
            }
        }
    }
}
