//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sotec_web.n11Api_TicketService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="n11Api_TicketService.TicketServicePort")]
    public interface TicketServicePort {
        
        // CODEGEN: TicketListingBelongsToSeller işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1 TicketListingBelongsToSeller(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1> TicketListingBelongsToSellerAsync(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 request);
        
        // CODEGEN: TicketListingAssignedToSeller işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1 TicketListingAssignedToSeller(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1> TicketListingAssignedToSellerAsync(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 request);
        
        // CODEGEN: TicketAnswer işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketAnswerResponse1 TicketAnswer(sotec_web.n11Api_TicketService.TicketAnswerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketAnswerResponse1> TicketAnswerAsync(sotec_web.n11Api_TicketService.TicketAnswerRequest1 request);
        
        // CODEGEN: TicketCreate işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketCreateResponse1 TicketCreate(sotec_web.n11Api_TicketService.TicketCreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketCreateResponse1> TicketCreateAsync(sotec_web.n11Api_TicketService.TicketCreateRequest1 request);
        
        // CODEGEN: TicketReasons işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketReasonsResponse1 TicketReasons(sotec_web.n11Api_TicketService.TicketReasonsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReasonsResponse1> TicketReasonsAsync(sotec_web.n11Api_TicketService.TicketReasonsRequest1 request);
        
        // CODEGEN: TicketRead işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sotec_web.n11Api_TicketService.TicketReadResponse1 TicketRead(sotec_web.n11Api_TicketService.TicketReadRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReadResponse1> TicketReadAsync(sotec_web.n11Api_TicketService.TicketReadRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketListingBelongsToSellerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long sellerIdField;
        
        private int firstField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("sellerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int first {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
                this.RaisePropertyChanged("first");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ReasonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string isRequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string isRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
                this.RaisePropertyChanged("isRequired");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class AnswerDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string contentField;
        
        private string createDateField;
        
        private PersonDto creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PersonDto creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("creator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class PersonDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string nickNameField;
        
        private string emailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
                this.RaisePropertyChanged("nickName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class QuestionGroupDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oPENEDField;
        
        private string cLOSEDField;
        
        private string wAITINGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OPENED {
            get {
                return this.oPENEDField;
            }
            set {
                this.oPENEDField = value;
                this.RaisePropertyChanged("OPENED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLOSED {
            get {
                return this.cLOSEDField;
            }
            set {
                this.cLOSEDField = value;
                this.RaisePropertyChanged("CLOSED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WAITING {
            get {
                return this.wAITINGField;
            }
            set {
                this.wAITINGField = value;
                this.RaisePropertyChanged("WAITING");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long ticketIdField;
        
        private string headerField;
        
        private string contentField;
        
        private System.DateTime createDateField;
        
        private TicketStatus ticketStatusField;
        
        private PersonDto creatorField;
        
        private PersonDto sellerField;
        
        private QuestionGroupDto reasonField;
        
        private AnswerDto[] answersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long ticketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("ticketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public TicketStatus ticketStatus {
            get {
                return this.ticketStatusField;
            }
            set {
                this.ticketStatusField = value;
                this.RaisePropertyChanged("ticketStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public PersonDto creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("creator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public PersonDto seller {
            get {
                return this.sellerField;
            }
            set {
                this.sellerField = value;
                this.RaisePropertyChanged("seller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public QuestionGroupDto reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("answer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AnswerDto[] answers {
            get {
                return this.answersField;
            }
            set {
                this.answersField = value;
                this.RaisePropertyChanged("answers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketListingBelongsToSellerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private TicketDto ticketField;
        
        private TicketDto[] ticketListField;
        
        private PersonDto creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TicketDto ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ticket", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TicketDto[] ticketList {
            get {
                return this.ticketListField;
            }
            set {
                this.ticketListField = value;
                this.RaisePropertyChanged("ticketList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PersonDto creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("creator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketListingBelongsToSellerRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest TicketListingBelongsToSellerRequest;
        
        public TicketListingBelongsToSellerRequest1() {
        }
        
        public TicketListingBelongsToSellerRequest1(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest TicketListingBelongsToSellerRequest) {
            this.TicketListingBelongsToSellerRequest = TicketListingBelongsToSellerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketListingBelongsToSellerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse TicketListingBelongsToSellerResponse;
        
        public TicketListingBelongsToSellerResponse1() {
        }
        
        public TicketListingBelongsToSellerResponse1(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse TicketListingBelongsToSellerResponse) {
            this.TicketListingBelongsToSellerResponse = TicketListingBelongsToSellerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketListingAssignedToSellerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long sellerIdField;
        
        private int firstField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("sellerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int first {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
                this.RaisePropertyChanged("first");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketListingAssignedToSellerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private TicketDto ticketField;
        
        private TicketDto[] ticketListField;
        
        private PersonDto sellerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TicketDto ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ticket", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TicketDto[] ticketList {
            get {
                return this.ticketListField;
            }
            set {
                this.ticketListField = value;
                this.RaisePropertyChanged("ticketList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PersonDto seller {
            get {
                return this.sellerField;
            }
            set {
                this.sellerField = value;
                this.RaisePropertyChanged("seller");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketListingAssignedToSellerRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest TicketListingAssignedToSellerRequest;
        
        public TicketListingAssignedToSellerRequest1() {
        }
        
        public TicketListingAssignedToSellerRequest1(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest TicketListingAssignedToSellerRequest) {
            this.TicketListingAssignedToSellerRequest = TicketListingAssignedToSellerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketListingAssignedToSellerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse TicketListingAssignedToSellerResponse;
        
        public TicketListingAssignedToSellerResponse1() {
        }
        
        public TicketListingAssignedToSellerResponse1(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse TicketListingAssignedToSellerResponse) {
            this.TicketListingAssignedToSellerResponse = TicketListingAssignedToSellerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketAnswerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long sellerIdField;
        
        private long ticketIdField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("sellerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long ticketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("ticketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketAnswerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketAnswerRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketAnswerRequest TicketAnswerRequest;
        
        public TicketAnswerRequest1() {
        }
        
        public TicketAnswerRequest1(sotec_web.n11Api_TicketService.TicketAnswerRequest TicketAnswerRequest) {
            this.TicketAnswerRequest = TicketAnswerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketAnswerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketAnswerResponse TicketAnswerResponse;
        
        public TicketAnswerResponse1() {
        }
        
        public TicketAnswerResponse1(sotec_web.n11Api_TicketService.TicketAnswerResponse TicketAnswerResponse) {
            this.TicketAnswerResponse = TicketAnswerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long reasonIdField;
        
        private long sellerIdField;
        
        private string headerField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long reasonId {
            get {
                return this.reasonIdField;
            }
            set {
                this.reasonIdField = value;
                this.RaisePropertyChanged("reasonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long sellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("sellerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketCreateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketCreateRequest TicketCreateRequest;
        
        public TicketCreateRequest1() {
        }
        
        public TicketCreateRequest1(sotec_web.n11Api_TicketService.TicketCreateRequest TicketCreateRequest) {
            this.TicketCreateRequest = TicketCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketCreateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketCreateResponse TicketCreateResponse;
        
        public TicketCreateResponse1() {
        }
        
        public TicketCreateResponse1(sotec_web.n11Api_TicketService.TicketCreateResponse TicketCreateResponse) {
            this.TicketCreateResponse = TicketCreateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketReasonsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketReasonsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReasonDto[] allTicketReasonsField;
        
        private ReasonDto reasonField;
        
        private ResultInfo resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("reason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ReasonDto[] allTicketReasons {
            get {
                return this.allTicketReasonsField;
            }
            set {
                this.allTicketReasonsField = value;
                this.RaisePropertyChanged("allTicketReasons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ReasonDto reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketReasonsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketReasonsRequest TicketReasonsRequest;
        
        public TicketReasonsRequest1() {
        }
        
        public TicketReasonsRequest1(sotec_web.n11Api_TicketService.TicketReasonsRequest TicketReasonsRequest) {
            this.TicketReasonsRequest = TicketReasonsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketReasonsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketReasonsResponse TicketReasonsResponse;
        
        public TicketReasonsResponse1() {
        }
        
        public TicketReasonsResponse1(sotec_web.n11Api_TicketService.TicketReasonsResponse TicketReasonsResponse) {
            this.TicketReasonsResponse = TicketReasonsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketReadRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long ticketIdField;
        
        private long sellerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long ticketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("ticketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long sellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("sellerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class TicketReadResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketReadRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketReadRequest TicketReadRequest;
        
        public TicketReadRequest1() {
        }
        
        public TicketReadRequest1(sotec_web.n11Api_TicketService.TicketReadRequest TicketReadRequest) {
            this.TicketReadRequest = TicketReadRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TicketReadResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public sotec_web.n11Api_TicketService.TicketReadResponse TicketReadResponse;
        
        public TicketReadResponse1() {
        }
        
        public TicketReadResponse1(sotec_web.n11Api_TicketService.TicketReadResponse TicketReadResponse) {
            this.TicketReadResponse = TicketReadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TicketServicePortChannel : sotec_web.n11Api_TicketService.TicketServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketServicePortClient : System.ServiceModel.ClientBase<sotec_web.n11Api_TicketService.TicketServicePort>, sotec_web.n11Api_TicketService.TicketServicePort {
        
        public TicketServicePortClient() {
        }
        
        public TicketServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketListingBelongsToSeller(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 request) {
            return base.Channel.TicketListingBelongsToSeller(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse TicketListingBelongsToSeller(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest TicketListingBelongsToSellerRequest) {
            sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1();
            inValue.TicketListingBelongsToSellerRequest = TicketListingBelongsToSellerRequest;
            sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketListingBelongsToSeller(inValue);
            return retVal.TicketListingBelongsToSellerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketListingBelongsToSellerAsync(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 request) {
            return base.Channel.TicketListingBelongsToSellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingBelongsToSellerResponse1> TicketListingBelongsToSellerAsync(sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest TicketListingBelongsToSellerRequest) {
            sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketListingBelongsToSellerRequest1();
            inValue.TicketListingBelongsToSellerRequest = TicketListingBelongsToSellerRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketListingBelongsToSellerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketListingAssignedToSeller(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 request) {
            return base.Channel.TicketListingAssignedToSeller(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse TicketListingAssignedToSeller(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest TicketListingAssignedToSellerRequest) {
            sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1();
            inValue.TicketListingAssignedToSellerRequest = TicketListingAssignedToSellerRequest;
            sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketListingAssignedToSeller(inValue);
            return retVal.TicketListingAssignedToSellerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketListingAssignedToSellerAsync(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 request) {
            return base.Channel.TicketListingAssignedToSellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketListingAssignedToSellerResponse1> TicketListingAssignedToSellerAsync(sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest TicketListingAssignedToSellerRequest) {
            sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketListingAssignedToSellerRequest1();
            inValue.TicketListingAssignedToSellerRequest = TicketListingAssignedToSellerRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketListingAssignedToSellerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketAnswerResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketAnswer(sotec_web.n11Api_TicketService.TicketAnswerRequest1 request) {
            return base.Channel.TicketAnswer(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketAnswerResponse TicketAnswer(sotec_web.n11Api_TicketService.TicketAnswerRequest TicketAnswerRequest) {
            sotec_web.n11Api_TicketService.TicketAnswerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketAnswerRequest1();
            inValue.TicketAnswerRequest = TicketAnswerRequest;
            sotec_web.n11Api_TicketService.TicketAnswerResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketAnswer(inValue);
            return retVal.TicketAnswerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketAnswerResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketAnswerAsync(sotec_web.n11Api_TicketService.TicketAnswerRequest1 request) {
            return base.Channel.TicketAnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketAnswerResponse1> TicketAnswerAsync(sotec_web.n11Api_TicketService.TicketAnswerRequest TicketAnswerRequest) {
            sotec_web.n11Api_TicketService.TicketAnswerRequest1 inValue = new sotec_web.n11Api_TicketService.TicketAnswerRequest1();
            inValue.TicketAnswerRequest = TicketAnswerRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketAnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketCreateResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketCreate(sotec_web.n11Api_TicketService.TicketCreateRequest1 request) {
            return base.Channel.TicketCreate(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketCreateResponse TicketCreate(sotec_web.n11Api_TicketService.TicketCreateRequest TicketCreateRequest) {
            sotec_web.n11Api_TicketService.TicketCreateRequest1 inValue = new sotec_web.n11Api_TicketService.TicketCreateRequest1();
            inValue.TicketCreateRequest = TicketCreateRequest;
            sotec_web.n11Api_TicketService.TicketCreateResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketCreate(inValue);
            return retVal.TicketCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketCreateResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketCreateAsync(sotec_web.n11Api_TicketService.TicketCreateRequest1 request) {
            return base.Channel.TicketCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketCreateResponse1> TicketCreateAsync(sotec_web.n11Api_TicketService.TicketCreateRequest TicketCreateRequest) {
            sotec_web.n11Api_TicketService.TicketCreateRequest1 inValue = new sotec_web.n11Api_TicketService.TicketCreateRequest1();
            inValue.TicketCreateRequest = TicketCreateRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketCreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketReasonsResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketReasons(sotec_web.n11Api_TicketService.TicketReasonsRequest1 request) {
            return base.Channel.TicketReasons(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketReasonsResponse TicketReasons(sotec_web.n11Api_TicketService.TicketReasonsRequest TicketReasonsRequest) {
            sotec_web.n11Api_TicketService.TicketReasonsRequest1 inValue = new sotec_web.n11Api_TicketService.TicketReasonsRequest1();
            inValue.TicketReasonsRequest = TicketReasonsRequest;
            sotec_web.n11Api_TicketService.TicketReasonsResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketReasons(inValue);
            return retVal.TicketReasonsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReasonsResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketReasonsAsync(sotec_web.n11Api_TicketService.TicketReasonsRequest1 request) {
            return base.Channel.TicketReasonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReasonsResponse1> TicketReasonsAsync(sotec_web.n11Api_TicketService.TicketReasonsRequest TicketReasonsRequest) {
            sotec_web.n11Api_TicketService.TicketReasonsRequest1 inValue = new sotec_web.n11Api_TicketService.TicketReasonsRequest1();
            inValue.TicketReasonsRequest = TicketReasonsRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketReasonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sotec_web.n11Api_TicketService.TicketReadResponse1 sotec_web.n11Api_TicketService.TicketServicePort.TicketRead(sotec_web.n11Api_TicketService.TicketReadRequest1 request) {
            return base.Channel.TicketRead(request);
        }
        
        public sotec_web.n11Api_TicketService.TicketReadResponse TicketRead(sotec_web.n11Api_TicketService.TicketReadRequest TicketReadRequest) {
            sotec_web.n11Api_TicketService.TicketReadRequest1 inValue = new sotec_web.n11Api_TicketService.TicketReadRequest1();
            inValue.TicketReadRequest = TicketReadRequest;
            sotec_web.n11Api_TicketService.TicketReadResponse1 retVal = ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketRead(inValue);
            return retVal.TicketReadResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReadResponse1> sotec_web.n11Api_TicketService.TicketServicePort.TicketReadAsync(sotec_web.n11Api_TicketService.TicketReadRequest1 request) {
            return base.Channel.TicketReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<sotec_web.n11Api_TicketService.TicketReadResponse1> TicketReadAsync(sotec_web.n11Api_TicketService.TicketReadRequest TicketReadRequest) {
            sotec_web.n11Api_TicketService.TicketReadRequest1 inValue = new sotec_web.n11Api_TicketService.TicketReadRequest1();
            inValue.TicketReadRequest = TicketReadRequest;
            return ((sotec_web.n11Api_TicketService.TicketServicePort)(this)).TicketReadAsync(inValue);
        }
    }
}
